// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpEeI0T3Y35q_-DpaC85-mkz81jdiraNE',
    appId: '1:90395102027:web:ea056ccc83cf5fc8d7b6ce',
    messagingSenderId: '90395102027',
    projectId: 'loginapp-fa9da',
    authDomain: 'loginapp-fa9da.firebaseapp.com',
    storageBucket: 'loginapp-fa9da.appspot.com',
    measurementId: 'G-TXE5JCSZ3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY6eHXh92vgYI3n-qxM22-eqUDl52F5iY',
    appId: '1:90395102027:android:07fca810154b3382d7b6ce',
    messagingSenderId: '90395102027',
    projectId: 'loginapp-fa9da',
    storageBucket: 'loginapp-fa9da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeLWM4Qq5VFlLYgDjWj-SPBIrsmiJrYeU',
    appId: '1:90395102027:ios:6b95ccf875cf3114d7b6ce',
    messagingSenderId: '90395102027',
    projectId: 'loginapp-fa9da',
    storageBucket: 'loginapp-fa9da.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeLWM4Qq5VFlLYgDjWj-SPBIrsmiJrYeU',
    appId: '1:90395102027:ios:239fed6b469cc09fd7b6ce',
    messagingSenderId: '90395102027',
    projectId: 'loginapp-fa9da',
    storageBucket: 'loginapp-fa9da.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFirebase.RunnerTests',
  );
}
